import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Kadu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='de' className='scroll-smooth flex flex-col min-h-full'>
      <body className={`${inter.className} flex-1 flex flex-col`}>
        <Navigation />
        <div className='w-full pt-[84px] flex-1'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
